### ISSUE TITLE
SV_D has inverted sign

### ISSUE THREAD

**Issue by pre-martin** [ciaranbe/pyIGRF#1]
I think that the result of the yearly declination change rate (`SV_D`) is inverted.

`pyIGRF` is being called with these parameters:
* 1 - values at one location and date
* 2 - in decimal degrees
* lat and lon
* altitude `0`
* date `2020`

For lat=0 and lon=0 I get the following result (remark: SV_D is negative):
```
Geomagnetic field values at:  0.0° / 0.0°, at altitude 0.0 for 2020.0
Declination (D): -4.654 °
Declination SV (D): -10.06 arcmin/yr   (hint: -10.06/60=-0.167°)
````
As reference: https://www.ngdc.noaa.gov/geomag-web/calculators/calculateDeclination?lat1=0&lon1=0&startYear=2020&startMonth=1&resultFormat=xml returns (remark: SV_D is positive):
```
<declination_sv units="Degree"> 0.16277 </declination_sv>
```

For lat=0 and lon=150 the output of pyIGRF is as follows (remark: SV_D is positive):
```
Geomagnetic field values at:  0.0° / 150.0°, at altitude 0.0 for 2020.0
Declination (D):  4.998 °
Declination SV (D):  1.99 arcmin/yr    (hint: 1.99/60=0.033°)
```
As reference https://www.ngdc.noaa.gov/geomag-web/calculators/calculateDeclination?lat1=0&lon1=150&startYear=2020&startMonth=1&resultFormat=xml returns (remark: SV_D is negative):
```
<declination_sv units="Degree"> -0.02603 </declination_sv>
```

The behaviour can also be seen, when `pyIGRF` is called with
* 2 - values at yearly intervals at one location
* 2 - in decimal degrees
* 1 - geodetic (shape of Earth using the WGS-84 ellipsoid)
* lat and lon: 0 150
* altitude: 0
* date start: 2016
* date end: 2024

The resulting table (reduced to the columns in question):
```
Geomagnetic field values at:  0.0° / 150.0°, at altitude 0.0
Date  D(°)  SV_D(min/yr)
2016.0  5.128 1.95
2017.0  5.096 1.95
2018.0  5.063 1.95
2019.0  5.031 1.95
2020.0  4.998 1.99
2021.0  4.965 1.99
2022.0  4.932 1.99
2023.0  4.899 1.99
2024.0  4.865 1.99
```
The value `D` is getting smaller, but SV_D is always positive. Shouldn't it be negative?

**Comment by ciaranbe** [comment]
Thank you for pointing this bug out. You are correct that SV of Declination and Inclination were inverted in sign. I checked through the original igrf.f code this is based on https://www.ngdc.noaa.gov/IAGA/vmod/igrf13.f and found the lines of code computing SV_D and SV_I
```
      CALL IGRF13SYN (1,DATE,ITYPE,ALT,CLT,XLN,DX,DY,DZ,F1)
      DD = (60.0*FACT*(X*DY - Y*DX))/(H*H)
      DS = (60.0*FACT*(H*DZ - Z*DH))/(F*F)
```

Then I checked the igrf_utils.py code and found that the code to do this on Lines 625/26 had
```
    ddot = r2d((xdot*y - ydot*x)/h2)*60
    idot = r2d((hdot*z - h*zdot)/f2)*60
```

So the solution is to rearrange the  subtractions in the brackets to be 
```
    ddot = r2d((ydot*x - xdot*y)/h2)*60
    idot = r2d((h*zdot - hdot*z)/f2)*60
```

which corrects the sign of inclination and declination. This also provides the correct sense of change of D and I when computing the changes over time:
```
Geomagnetic field values at:  0.0° / 0.0°, at altitude 0.0
Date  D(°)  I(°)  H(nT) F(nT) X(nT) Y(nT)  Z(nT)     SV_D(min/yr)  SV_I(min/yr)  SV_H(nT/yr)  SV_F(nT/yr)  SV_X(nT/yr)  SV_Y(nT/yr)  SV_Z(nT/yr) 
2016.0 -5.282 -29.790  27663.8  31876.3  27546.4 -2546.5 -15837.0  9.39 -4.58 -8.8  14.1 -1.6  76.1 -43.8
2017.0 -5.125 -29.866  27655.4  31890.8  27544.8 -2470.4 -15880.9  9.39 -4.58 -8.8  14.1 -1.6  76.1 -43.8
2018.0 -4.968 -29.942  27647.1  31905.4  27543.2 -2394.3 -15924.7  9.39 -4.58 -8.8  14.1 -1.6  76.1 -43.8
2019.0 -4.811 -30.017  27639.0  31920.4  27541.6 -2318.2 -15968.6  9.39 -4.58 -8.8  14.1 -1.6  76.1 -43.8
2020.0 -4.654 -30.093  27631.1  31935.5  27540.0 -2242.1 -16012.4  10.06 -2.99 -14.5 -0.6 -7.9  81.8 -23.7
2021.0 -4.487 -30.142  27616.8  31935.0  27532.1 -2160.3 -16036.1  10.06 -2.99 -14.5 -0.6 -7.9  81.8 -23.7
2022.0 -4.319 -30.192  27602.6  31934.7  27524.2 -2078.6 -16059.9  10.06 -2.99 -14.5 -0.6 -7.9  81.8 -23.7
2023.0 -4.151 -30.241  27588.7  31934.6  27516.4 -1996.8 -16083.6  10.06 -2.99 -14.5 -0.6 -7.9  81.8 -23.7
2024.0 -3.982 -30.290  27575.1  31934.8  27508.5 -1915.0 -16107.4  10.06 -2.99 -14.5 -0.6 -7.9  81.8 -23.7
```
as D becomes less negative and SV_D is postive. 

A new version of igrf_utils.py has been committed (2ebc014)
