### ISSUE TITLE
optimization

### ISSUE THREAD

**Issue by bjackel** [ciaranbe/pyIGRF#4]
Thanks for providing a python IGRF.

Note that the scipy special function module has a "lpmn" method 

  P, dP = scipy.special.lpmn(n=degree, m=degree, z=np.cos(theta))

which appears to be  roughly 20x faster than the "legendre_poly" method in your code.  
 
  %timeit Pmn_z,Pmn_dz = specfun.lpmn(15,15, 0.45)
  %timeit Pmn_z = legendre_poly(15, 0.45)

  3.99 µs ± 36.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
  1.06 ms ± 9.64 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

This may be useful when evaluating the field at many times or locations. 

For an alternative example, see:

  https://github.com/bjackel/dbdt/blob/master/cgv/model/igrf/igrf_model.py

**Comment by ciaranbe** [comment]
Thank you for highlighting the new package with the optimised code. The code in this package comes from the original Malin and Barraclough paper (Malin, S. R. C., and D. R. Barraclough. "An algorithm for synthesizing the geomagnetic field." Computers & Geosciences 7.4 (1981): 401-405.) so can surely be updated.

Related to Issue 2, it is probably a good idea to develop a more official version of the code from the IAGA committee who help put together the coefficients every five years. I can certainly incorporate the scipy function at that stage.
